---
language: ruby

before_install:
  gem install bundler -v 2.1.4

cache:
  bundler: true

script: bundle exec rake

jobs:
  include:
    - rvm: 2.4.10
    - rvm: 2.5.8
    - rvm: 2.6.6
    - rvm: 2.7.1
    - rvm: 2.7.1
      name: "RuboCop"
      script: bundle exec rubocop

branches:
  only:
    - master
